apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "go-semver"
  labels:
    snyk.io/businessCriticality: medium
    snyk.io/visibility: private
    snyk.io/metadata-version: "2021-14-10"
spec:
  type: library
  lifecycle: production
  owner: "@snyk/flow"
